import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { Header } from "@/components/header";
import { ThemeProvider } from "next-themes";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Linguolink",
	description: "Generated by gokhanozturk.io",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable,
				)}
			>
				<>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
						<Header />
						{children}
					</ThemeProvider>
				</>
			</body>
		</html>
	);
}
